### ISSUE TITLE
checklist for next release 1.04

### ISSUE THREAD

**Issue by fenugrec** [fenugrec/nisprog#8]
TODO

- [x] bump version # in build sys and docs
- [x] update docs with changed commands (setdev, dump all, ...)
- [x] update error defs to match latest npkern
- [x] update ECUID-KEY list
- [x] test with latest npkern (https://github.com/fenugrec/npkern/issues/3 )

**Comment by periperidip** [comment]
Hey @fenugrec ! Are you open to contributions on this repo? Or is this a personal project? I would love to learn about ECU programming and diagnostic tools, would love to start with this!

**Comment by fenugrec** [comment]
Hi,
yes absolutely!
Of course as you can see, with a few exceptions I'm the only one working on this.
How did you find this project, via the romraider forums or somewhere else ?

**Comment by Phalp** [comment]
Holy crap. Do you know how good it feels to see these messages in my email inbox? Lol

**Comment by periperidip** [comment]
> Hi,
> yes absolutely!

Thanks a lot! I will start studying the code today and figure out what's up. Any pointers I should keep in mind?

> Of course as you can see, with a few exceptions I'm the only one working on this.
> How did you find this project, via the romraider forums or somewhere else ?

I think I found this by just searching "Open source ECU tools" or something.'

Edit: I thought this thread was on the `freediag` repo. I came to `nisprog` from the `freediag` repo.

**Comment by fenugrec** [comment]
> Edit: I thought this thread was on the `freediag` repo. I came to `nisprog` from the `freediag` repo.

Ah yes. Nisprog uses the core part of freediag (`libdiag`) as a backend, but adds Nissan-specific code for a certain generation of their ECUs in particular (~ 2001-2007 roughly). Freediag is a more general-purpose project.

Depending on your interests, there's plenty of room for improvement in both these projects. Or if you feel like resurrecting a project, I had also started work on an opensource J2534 interface... if you want, email me at "my username" @ users.sourceforge.net.

**Comment by periperidip** [comment]
I would actually like some starter material on diagnostic tools if you got any: articles, videos, blogs anything would work! I do not have a particular niche or interest as of now since I am not very aware of what the internals of diagnostic tools and ECU programming are.

I have started to study the source code of `freediag`. Where would you suggest I start? How did you start out?

So, the email is `<github-username>@users.sourceforge.net`?

**Comment by fenugrec** [comment]
release tagged @ 29a6f10
